URL_ATLA_N = 'Data/ATLA-N.xlsx'
URL_ATLA_S = 'Data/ATLA-S.xlsx'
URL_NINO = 'Data/NIÑO.xlsx'
URL_PAC_S = 'Data/PAC-S.xlsx'
URL_PANOM_MENSAL_CATEGORIZADA = 'Data/PANOM-MENSAL-CATEGORIZADA.xlsx'
URL_PANOM_MENSAL = 'Data/PANOM-MENSAL.xlsx'
URL_PRP_MENSAL = 'Data/PRP-MENSAL.xlsx'

