URL_ATLA_N = 'Data/ATLA-N.xlsx'
URL_ATLA_S = 'Data/ATLA-S.xlsx'
URL_NINO = 'Data/NIÑO.xlsx'
URL_PAC_S = 'Data/PAC-S.xlsx'
URL_PANOM_MENSAL_CATEGORIZADA = 'Data/PANOM-MENSAL-CATEGORIZADA.xlsx'
URL_PANOM_MENSAL = 'Data/PANOM-MENSAL.xlsx'
URL_PRP_MENSAL = 'Data/PRP-MENSAL.xlsx'
URL_COORDENADAS='Data/COORDENADAS.xlsx'


__all__ = ['URL_ATLA_N', 'URL_ATLA_S', 'URL_NINO', 'URL_PAC_S', 
           'URL_PANOM_MENSAL_CATEGORIZADA', 'URL_PANOM_MENSAL', 'URL_PRP_MENSAL', 'URL_COORDENADAS']